import type { RawDanmu, CommanderMapKey } from '@qier-player/danmaku/dist/es/main/types';

export const danmusData: (RawDanmu & { position: CommanderMapKey, timestatamp: number, checked?: boolean })[]  = [
  {
    text: '死亡搁浅！',
    color: '#f00',
    position: 'fixed-top',
    timestatamp: 0.4,
  },
  {
    text: '死亡搁浅！！',
    color: '#f00',
    position: 'fixed-top',
    timestatamp: 0.4,
  },
  {
    text: '死亡搁浅！！！',
    color: '#f00',
    position: 'fixed-top',
    timestatamp: 0.4,
  },
  {
    text: '小岛秀夫yyds',
    color: '#fff',
    position: 'rolling',
    timestatamp: 1.2,
  },
  {
    text: '这部作品什么时候出下一部啊，好期待',
    color: '#fff',
    position: 'rolling',
    timestatamp: 1.2,
  },
  {
    text: '生存之旅',
    color: '#00f',
    position: 'fixed-top',
    timestatamp: 1.2,
  },
  {
    text: '我爱死亡搁浅！',
    color: '#f0f',
    position: 'rolling',
    timestatamp: 1.3,
  },
  {
    text: '布里吉特的故事真挺感人的',
    color: '#ff0',
    position: 'fixed-bottom',
    timestatamp: 1.3,
  },
  {
    text: '希望能再见到山姆啊啊啊',
    color: '#fff',
    position: 'rolling',
    timestatamp: 1.3,
  },
  {
    text: '死亡搁浅的画面太美了，感觉像看电影',
    color: '#0f0',
    position: 'fixed-top',
    timestatamp: 1.4,
  },
  {
    text: '你们觉得二代会怎样？',
    color: '#f90',
    position: 'rolling',
    timestatamp: 1.5,
  },
  {
    text: '这游戏的音乐绝绝子',
    color: '#fff',
    position: 'fixed-bottom',
    timestatamp: 1.5,
  },
  {
    text: '期待更多的剧情展开',
    color: '#0ff',
    position: 'fixed-top',
    timestatamp: 3,
  },
  {
    text: '死神与连接的故事！',
    color: '#f00',
    position: 'rolling',
    timestatamp: 3.4,
  },
  {
    text: '克劳斯好帅啊',
    color: '#fff',
    position: 'fixed-bottom',
    timestatamp: 3.5,
  },
  {
    text: '每次冒险都令人心跳加速',
    color: '#f00',
    position: 'fixed-top',
    timestatamp: 4.5,
  },
  {
    text: '死亡搁浅的玩法真挺独特',
    color: '#ff0',
    position: 'rolling',
    timestatamp: 4.5,
  },
  {
    text: '山姆的背影让我心疼',
    color: '#0f0',
    position: 'fixed-bottom',
    timestatamp: 5,
  },
  {
    text: '这游戏的设定太棒了',
    color: '#00f',
    position: 'rolling',
    timestatamp: 5.2,
  },
  {
    text: '真希望能有续集',
    color: '#f0f',
    position: 'fixed-top',
    timestatamp: 6.2,
  },
  {
    text: '连结的意义真深刻',
    color: '#0ff',
    position: 'rolling',
    timestatamp: 7.2,
  },
  {
    text: '画面美得不可思议',
    color: '#fff',
    position: 'fixed-bottom',
    timestatamp: 9.2,
  },
  {
    text: '孤独感和希望并存！',
    color: '#f90',
    position: 'fixed-top',
    timestatamp: 10.2,
  },
  {
    text: '为山姆加油！',
    color: '#fff',
    position: 'rolling',
    timestatamp: 11.2,
  },
  {
    text: '死亡搁浅的世界好迷人！',
    color: '#00f',
    position: 'fixed-bottom',
    timestatamp: 12.2,
  },
  {
    text: '这段生存挑战挺有意思的。',
    color: '#00f',
    position: 'fixed-top',
    timestatamp: 13,
  },
  {
    text: '故事情节吸引人。',
    color: '#f0f',
    position: 'rolling',
    timestatamp: 14,
  },
  {
    text: '在探索未知的旅程',
    color: '#ff0',
    position: 'fixed-bottom',
    timestatamp: 16,
  },
  {
    text: '感觉到一种连接和孤独。',
    color: '#fff',
    position: 'rolling',
    timestatamp: 16,
  },
  {
    text: '山姆的经历很特别。',
    color: '#0f0',
    position: 'fixed-top',
    timestatamp: 12,
  },
  {
    text: '主题确实很深刻。',
    color: '#f90',
    position: 'rolling',
    timestatamp: 14,
  },
  {
    text: '音乐的选择很好。',
    color: '#fff',
    position: 'fixed-bottom',
    timestatamp: 11.2,
  },
  {
    text: '沉浸感很强。',
    color: '#0ff',
    position: 'fixed-top',
    timestatamp: 13.2,
  },
  {
    text: '对未来的故事很期待。',
    color: '#f00',
    position: 'rolling',
    timestatamp: 14.2,
  },
  {
    text: '这种体验很独特。',
    color: '#fff',
    position: 'fixed-bottom',
    timestatamp: 4.2,
  },
]
