name: Deploy QierPlayer Docs to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn # 或 pnpm / npm
      - name: Build
        working-directory: ./website
        run: yarn && yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          branch: gh-pages
          folder: website/docs/.vitepress/dist
